# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file builds the master prompt for the root MySQL agent, 
# including the context generated by the generate_mysql_prompt.py file.

import os

def _load_mysql_context(filename: str = "enhanced_mysql_prompt.txt") -> str:
    """
    Loads the detailed MySQL database context from a file.
    This content is generated by the `generate_mysql_prompt.py` script.
    
    Args:
        filename (str): The name of the context file to read.

    Returns:
        str: The content of the file, or a warning/error message if it fails.
    """
    try:
        # Assumes the context file is in the same directory as this script.
        # Adjust the path if your project structure is different.
        base_path = os.path.dirname(__file__)
        context_file_path = os.path.join(base_path, filename)

        with open(context_file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        print(f"MySQL context loaded successfully from '{filename}'")
        return content

    except FileNotFoundError:
        error_message = (f"WARNING: The context file '{filename}' was not found.\n"
                         "Please run the 'generate_mysql_prompt.py' script to create it.")
        print(error_message)
        return "## WARNING: MySQL context is not available.\n## Run the 'generate_mysql_prompt.py' script to populate this section."
    except Exception as e:
        error_message = f"An error occurred while loading the prompt context: {e}"
        print(error_message)
        return f"## ERROR: Could not load MySQL context.\n## Details: {e}"

# 1. Load the dynamic context from the file.
MYSQL_PROMPT_CONTEXT = _load_mysql_context()

# 2. Define the main prompt for the agent.
MYSQL_PROMPT = f"""
# ROLE AND GOAL
You are an expert MySQL database developer and a helpful assistant. Your primary goal is to understand a user's question, formulate the correct SQL query based on the detailed database context provided below, execute it using the available `query_mysql` tool, and then present the results to the user in a clear, concise, and friendly manner.

**Execution Flow:**
1.  **Analyze the user's request** to understand their intent.
2.  **Construct a single, valid MySQL query** based on the user's request and the extensive database context below. The query must be on a single line.
3.  **Call the `query_mysql` tool** with the generated SQL string as the argument.
4.  **Receive the JSON response** from the tool. The response will be a dictionary with a 'data' key containing a list of rows, or an 'error' key.
5.  **Analyze the result.** If there's data, summarize it into a user-friendly, natural language answer. Do not just dump the raw JSON. Format lists or tables nicely. If there's an error, explain it clearly to the user.

# DATABASE CONTEXT AND EXAMPLES

{MYSQL_PROMPT_CONTEXT}

"""
